### ISSUE TITLE
Facebook Ads not showing (iOS)

### ISSUE THREAD

**Issue by winonline** [floatinghotpot/cordova-plugin-facebookads#26]
Banner and Interstitial are not working when I archived my package to apple. I made an internal test loading my package from app store and Ads are not working. Running from my mac in debug mode is working fine but isTesting property is also not working. The problem is for iOS only. Android is working.

p.s. I also tried Admob Pro (working), and iAd (similar problem - banner in debug mode is fine, interstitial is not working)

**Comment by floatinghotpot** [comment]
Did you get your app id approved by Facebook guys?

**Comment by winonline** [comment]
Thank you for very quick response. Yes, I have. I also use my app id with android and it's working. The big problem is it's not working with my uploaded ipa. Debuging mode is working.

**Comment by quantumcept** [comment]
Having the same issue. Works fine on ios simulator but does not work on my iphone.

**Comment by winonline** [comment]
For Facebook Ads only, it's not working for TestFlight. My app has just on sale and ads are showing correctly on my iPhone. If you have this issue, please make sure that you download from App Store not TestFlight.

**Comment by quantumcept** [comment]
@winonline did you have to submit an app with no ads and get it approved first by iTunes Connect then get it approved by facebook. And after the facebook approval, reupload with ads and get it approved by iTunes Connect?

Currently I submitted my app to iTunes Connect, but I am getting rejected because they cannot see the banner ad at the bottom of the screen. I would appreciate your response, Thanks.

Facebook says ads are approved but I cannot add my app to the portal because apple does not approve my app. 
<img width="249" alt="screen shot 2016-01-05 at 10 02 03 pm" src="https://cloud.githubusercontent.com/assets/12467465/12135996/187919a8-b3f8-11e5-8fa6-93503fc1f688.png">

<img width="814" alt="screen shot 2016-01-05 at 10 00 50 pm" src="https://cloud.githubusercontent.com/assets/12467465/12135998/1f403f28-b3f8-11e5-94f0-fb95f7fd58db.png">

**Comment by winonline** [comment]
@quantumcept You need to submit an app with ads. It's quite simple. If you did it correctly, you will see your ads on your device when you debug your program with xcode. Connect your device to your mac and start debugging. I recommend you to capture the screen with ads and reply to Apple review team. They may need a captured picture to see where your ads located. I did this way once and I got approve later on.

Again with debug you will see ads but with TestFlight you will not see any ads.

Good luck

**Comment by haihoang1993** [comment]
thank!
